#!/usr/bin/env python3
"""Episode 7 figure: the autonomous committee lineage on real TUM (Track A).

Panel A: held-out ATE per lineage experiment (the committee's autonomous search + the
best-so-far envelope + the graceful failure). Panel B: the best-found config's trajectory
vs ground truth. Data is read from the committee run's registry; the trajectory is
regenerated by running the reference VO at the winning params on the cached frames.
"""
from __future__ import annotations
import json, os, sqlite3, subprocess, sys, tempfile
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "artifacts" / "blog"; OUT.mkdir(parents=True, exist_ok=True)
DB = ROOT / "_vo_tum_committee_run/state/registry.db"
FRAMES = ROOT / "_vo_tum_impl_run/cache/data/vo-tum-frames"
GT = ROOT / "_vo_tum_impl_run/cache/heldout/vo-tum-gt/gt.txt"


def lineage():
    con = sqlite3.connect(DB)
    rows = []
    for rid, data in con.execute("SELECT id,data FROM experiments WHERE id LIKE 'vo-real-%'"):
        d = json.loads(data)
        v = d.get("verdict") or {}; mm = v.get("measured_metrics") or {}
        cmd = (d.get("contract") or {}).get("command", "")
        p = {t.split("=")[0].replace("LAB_", ""): t.split("=")[1]
             for t in cmd.split() if "=" in t and "LAB_" in t}
        # only completed experiments — a PROPOSED one was interrupted when the run was
        # stopped, not a genuine outcome, so it must not appear as a failure.
        if d.get("status") in ("VERIFIED", "REJECTED", "FAILED"):
            rows.append((d.get("created_at", ""), rid, d.get("status"), mm.get("ate_rmse"), p))
    return sorted(rows)


def umeyama_sim3(src, dst):
    n = len(src); mu_s, mu_d = src.mean(0), dst.mean(0); Xs, Xd = src - mu_s, dst - mu_d
    vs = (Xs ** 2).sum() / n; U, D, Vt = np.linalg.svd((Xd.T @ Xs) / n); S = np.eye(3)
    if np.linalg.det(U) * np.linalg.det(Vt) < 0: S[-1, -1] = -1
    R = U @ S @ Vt; s = np.trace(np.diag(D) @ S) / vs
    return (s * (R @ src.T)).T + (mu_d - s * R @ mu_s)


def run_vo(nf, ransac, ratio):
    tmp = Path(tempfile.mkdtemp())
    env = dict(os.environ, LAB_DATA=str(FRAMES), LAB_ARTIFACTS=str(tmp),
               LAB_NFEATURES=str(nf), LAB_RANSAC_THRESH=str(ransac), LAB_RATIO=str(ratio))
    subprocess.run([sys.executable, str(ROOT / "vo_lab/plugins/vo_ref/run.py")], env=env,
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return np.loadtxt(tmp / "traj.txt").reshape(-1, 3)


def main():
    rows = lineage()
    fig, (axA, axB) = plt.subplots(1, 2, figsize=(12, 5))

    # Panel A: ATE per experiment + best-so-far envelope
    xs, ates, labels, best_so_far, best = [], [], [], [], 1e9
    for i, (_, rid, st, ate, p) in enumerate(rows, 1):
        xs.append(i); labels.append(rid.replace("vo-real-", "#"))
        if ate:
            ates.append(ate); best = min(best, ate)
        else:
            ates.append(None)
        best_so_far.append(best if best < 1e9 else None)
    vx = [x for x, a in zip(xs, ates) if a]; va = [a for a in ates if a]
    axA.plot(vx, va, "o-", color="#1a9850", ms=9, lw=1.5, label="verified experiment (held-out ATE)")
    fx = [x for x, a in zip(xs, ates) if a is None]
    for x in fx:
        axA.scatter([x], [max(va) * 1.02], marker="x", s=90, color="#d73027", zorder=5,
                    label="failed (menu error, loop survived)" if x == fx[0] else None)
    axA.plot(xs, best_so_far, "--", color="#888", lw=1.5, label="best-so-far")
    bi = int(np.argmin(va))
    axA.annotate(f"best {va[bi]:.3f} m", (vx[bi], va[bi]), textcoords="offset points",
                 xytext=(0, -22), ha="center", fontweight="bold")
    axA.set_xticks(xs); axA.set_xticklabels(labels)
    axA.set_ylabel("held-out ATE (m, Sim3)"); axA.set_xlabel("lineage experiment")
    axA.set_title("A. The committee's autonomous search\n0.155 → 0.114 m (−26%)", fontweight="bold")
    axA.grid(alpha=0.3); axA.legend(fontsize=8)

    # Panel B: best-config trajectory vs GT
    best_row = min((r for r in rows if r[3]), key=lambda r: r[3])
    p = best_row[4]
    est = run_vo(p.get("NFEATURES", 600), p.get("RANSAC_THRESH", 1.0), p.get("RATIO", 0.0))
    gt = np.loadtxt(GT).reshape(-1, 3); m = min(len(est), len(gt))
    al = umeyama_sim3(est[:m], gt[:m]); g = gt[:m]
    axB.plot(g[:, 0], g[:, 2], "k-", lw=2, label="ground truth")
    axB.plot(al[:, 0], al[:, 2], "-", color="#1a9850", lw=1.4,
             label=f"best config (nf={p.get('NFEATURES')}, ratio={p.get('RATIO')})")
    axB.scatter([g[0, 0]], [g[0, 2]], c="green", s=40, zorder=5)
    axB.set_title("B. Best-found config vs ground truth", fontweight="bold")
    axB.set_xlabel("X (m)"); axB.set_ylabel("Z (m)")
    axB.set_aspect("equal", "datalim"); axB.grid(alpha=0.3); axB.legend(fontsize=8)

    fig.suptitle("Episode 7 — Track A: an autonomous committee runs a research program (real TUM)",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    pth = OUT / "ep7_committee.png"
    fig.savefig(pth, dpi=130, bbox_inches="tight"); plt.close(fig)
    print("wrote", pth)


if __name__ == "__main__":
    main()
